name: Auto Build Deploy Client
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - '**.json'
      - '**.css'
      - '**.png'
      - '**.svg'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: write secret
        shell: python
        run: |
          with open("pass", "w") as f: f.write("${{ secrets.SSH_PASS }}")

      - name: deploy
        run: |
          sshpass \
            -f pass \
            ssh \
              -o 'StrictHostKeyChecking no' \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              'cd /root/selendra-explorer-nextjs && git checkout main && git checkout . && git pull --rebase && npm i --force && npm run build && pm2 restart 4'
